"""Convert data field to Date type

Revision ID: c651883b8a77
Revises: 
Create Date: 2025-07-07 13:33:31.704982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c651883b8a77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('vale_alimentacao', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('entrada1', sa.String(length=5), nullable=True),
    sa.Column('saida1', sa.String(length=5), nullable=True),
    sa.Column('entrada2', sa.String(length=5), nullable=True),
    sa.Column('saida2', sa.String(length=5), nullable=True),
    sa.Column('entrada3', sa.String(length=5), nullable=True),
    sa.Column('saida3', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ponto')
    op.drop_table('funcionario')
    op.drop_table('empresa')
    # ### end Alembic commands ###
